package io.github.miklires.mauction;

import org.h2.Driver;import java.nio.file.Path;import java.sql.*;import java.time.*;import java.util.*;import java.util.concurrent.*;
public final class AuctionRepository implements AutoCloseable{
 private final String url;private final ExecutorService executor=Executors.newSingleThreadExecutor(Thread.ofVirtual().name("mauction-db-",0).factory());
 public AuctionRepository(Path file){this("jdbc:h2:"+file.toAbsolutePath()+";AUTO_SERVER=TRUE");}AuctionRepository(String url){this.url=url;}
 public CompletableFuture<Void>initialize(){return run(()->{try(Connection c=open();Statement s=c.createStatement()){s.executeUpdate("CREATE TABLE IF NOT EXISTS listings(id UUID PRIMARY KEY,seller UUID NOT NULL,seller_name VARCHAR(32) NOT NULL,item BINARY LARGE OBJECT NOT NULL,price DOUBLE PRECISION NOT NULL,state VARCHAR(16) NOT NULL,buyer UUID,created_at TIMESTAMP WITH TIME ZONE NOT NULL,expires_at TIMESTAMP WITH TIME ZONE NOT NULL)");s.executeUpdate("CREATE TABLE IF NOT EXISTS purchases(tx UUID PRIMARY KEY,listing_id UUID NOT NULL,buyer UUID NOT NULL,buyer_name VARCHAR(32) NOT NULL,stage VARCHAR(24) NOT NULL,created_at TIMESTAMP WITH TIME ZONE NOT NULL)");}});}
 public CompletableFuture<Listing>create(UUID seller,String name,byte[]item,double price,Instant expires){return supply(()->{UUID id=UUID.randomUUID();Instant now=Instant.now();try(Connection c=open();PreparedStatement p=c.prepareStatement("INSERT INTO listings VALUES(?,?,?,?,?,'ACTIVE',NULL,?,?)")){p.setObject(1,id);p.setObject(2,seller);p.setString(3,name);p.setBytes(4,item);p.setDouble(5,price);p.setObject(6,now);p.setObject(7,expires);p.executeUpdate();}return new Listing(id,seller,name,item,price,ListingState.ACTIVE,null,now,expires);});}
 public CompletableFuture<List<Listing>>active(int limit){return supply(()->{List<Listing>out=new ArrayList<>();try(Connection c=open();PreparedStatement expire=c.prepareStatement("UPDATE listings SET state='EXPIRED' WHERE state='ACTIVE' AND expires_at<?")){expire.setObject(1,Instant.now());expire.executeUpdate();}try(Connection c=open();PreparedStatement p=c.prepareStatement("SELECT * FROM listings WHERE state='ACTIVE' ORDER BY created_at DESC FETCH FIRST ? ROWS ONLY")){p.setInt(1,limit);try(ResultSet r=p.executeQuery()){while(r.next())out.add(map(r));}}return List.copyOf(out);});}
 public CompletableFuture<Long>activeCount(UUID seller){return supply(()->{try(Connection c=open();PreparedStatement p=c.prepareStatement("SELECT COUNT(*) FROM listings WHERE seller=? AND state IN ('ACTIVE','RESERVED')")){p.setObject(1,seller);try(ResultSet r=p.executeQuery()){r.next();return r.getLong(1);}}});}
 public CompletableFuture<PurchaseResult>reserve(UUID listing,UUID buyer,String buyerName){return supply(()->{try(Connection c=open()){c.setAutoCommit(false);try{Listing value;try(PreparedStatement p=c.prepareStatement("SELECT * FROM listings WHERE id=? FOR UPDATE")){p.setObject(1,listing);try(ResultSet r=p.executeQuery()){if(!r.next()){c.rollback();return PurchaseResult.rejected(PurchaseResult.Status.NOT_FOUND);}value=map(r);}}if(value.seller().equals(buyer)){c.rollback();return PurchaseResult.rejected(PurchaseResult.Status.OWN_LISTING);}if(value.state()!=ListingState.ACTIVE||value.expiresAt().isBefore(Instant.now())){c.rollback();return PurchaseResult.rejected(PurchaseResult.Status.NOT_ACTIVE);}UUID tx=UUID.randomUUID();try(PreparedStatement p=c.prepareStatement("UPDATE listings SET state='RESERVED',buyer=? WHERE id=? AND state='ACTIVE'")){p.setObject(1,buyer);p.setObject(2,listing);if(p.executeUpdate()!=1){c.rollback();return PurchaseResult.rejected(PurchaseResult.Status.NOT_ACTIVE);}}try(PreparedStatement p=c.prepareStatement("INSERT INTO purchases VALUES(?,?,?,?,'RESERVED',?)")){p.setObject(1,tx);p.setObject(2,listing);p.setObject(3,buyer);p.setString(4,buyerName);p.setObject(5,Instant.now());p.executeUpdate();}c.commit();return new PurchaseResult(PurchaseResult.Status.RESERVED,value,tx);}catch(Throwable e){c.rollback();throw e;}finally{c.setAutoCommit(true);}}});}
 public CompletableFuture<Void>stage(UUID tx,String stage){return run(()->{try(Connection c=open();PreparedStatement p=c.prepareStatement("UPDATE purchases SET stage=? WHERE tx=?")){p.setString(1,stage);p.setObject(2,tx);p.executeUpdate();}});}
 public CompletableFuture<Void>release(UUID tx,UUID listing){return run(()->{try(Connection c=open()){c.setAutoCommit(false);try(PreparedStatement p=c.prepareStatement("UPDATE listings SET state='ACTIVE',buyer=NULL WHERE id=? AND state='RESERVED'")){p.setObject(1,listing);p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("UPDATE purchases SET stage='RELEASED' WHERE tx=?")){p.setObject(1,tx);p.executeUpdate();}c.commit();}});}
 public CompletableFuture<Void>sold(UUID tx,UUID listing){return run(()->{try(Connection c=open()){c.setAutoCommit(false);try(PreparedStatement p=c.prepareStatement("UPDATE listings SET state='SOLD' WHERE id=? AND state='RESERVED'")){p.setObject(1,listing);p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("UPDATE purchases SET stage='ITEM_PENDING' WHERE tx=?")){p.setObject(1,tx);p.executeUpdate();}c.commit();}});}
 public CompletableFuture<Optional<Listing>>cancel(UUID id,UUID actor,boolean admin){return supply(()->{try(Connection c=open()){c.setAutoCommit(false);try{Listing listing;try(PreparedStatement p=c.prepareStatement("SELECT * FROM listings WHERE id=? FOR UPDATE")){p.setObject(1,id);try(ResultSet r=p.executeQuery()){if(!r.next()){c.rollback();return Optional.empty();}listing=map(r);}}if(listing.state()!=ListingState.ACTIVE||!admin&&!listing.seller().equals(actor)){c.rollback();return Optional.empty();}try(PreparedStatement p=c.prepareStatement("UPDATE listings SET state='CANCELLED' WHERE id=?")){p.setObject(1,id);p.executeUpdate();}c.commit();return Optional.of(listing);}catch(Throwable e){c.rollback();throw e;}finally{c.setAutoCommit(true);}}});}
 private static Listing map(ResultSet r)throws SQLException{return new Listing(r.getObject("id",UUID.class),r.getObject("seller",UUID.class),r.getString("seller_name"),r.getBytes("item"),r.getDouble("price"),ListingState.valueOf(r.getString("state")),r.getObject("buyer",UUID.class),r.getObject("created_at",OffsetDateTime.class).toInstant(),r.getObject("expires_at",OffsetDateTime.class).toInstant());}
 private Connection open()throws SQLException{Properties p=new Properties();p.setProperty("user","sa");p.setProperty("password","");return new Driver().connect(url,p);}private<T>CompletableFuture<T>supply(SqlSupplier<T>task){return CompletableFuture.supplyAsync(()->{try{return task.get();}catch(Exception e){throw new CompletionException(e);}},executor);}private CompletableFuture<Void>run(SqlRunnable task){return supply(()->{task.run();return null;});}@Override public void close(){executor.shutdown();}@FunctionalInterface private interface SqlSupplier<T>{T get()throws Exception;}@FunctionalInterface private interface SqlRunnable{void run()throws Exception;}
}
