package io.github.miklires.mauction;

import org.h2.Driver;
import java.nio.file.Path;
import java.sql.*;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;

public final class AuctionRepository implements AutoCloseable {
    public enum SortOrder { NEWEST, PRICE_LOW, PRICE_HIGH, EXPIRING; public SortOrder next(){return values()[(ordinal()+1)%values().length];} }
    public record BrowsePage(List<Listing> listings,int total,int page,int pages){ public BrowsePage{listings=List.copyOf(listings);} }
    private final String url;
    private final ExecutorService executor=Executors.newSingleThreadExecutor(Thread.ofVirtual().name("mauction-db-",0).factory());
    public AuctionRepository(Path file){this("jdbc:h2:"+file.toAbsolutePath()+";AUTO_SERVER=TRUE");}
    AuctionRepository(String url){this.url=url;}

    public CompletableFuture<Void> initialize(){return run(()->{try(Connection c=open();Statement s=c.createStatement()){
        s.executeUpdate("CREATE TABLE IF NOT EXISTS schema_version(version INT NOT NULL)");
        s.executeUpdate("CREATE TABLE IF NOT EXISTS listings(id UUID PRIMARY KEY,seller UUID NOT NULL,seller_name VARCHAR(32) NOT NULL,item BINARY LARGE OBJECT NOT NULL,price DOUBLE PRECISION NOT NULL,state VARCHAR(16) NOT NULL,buyer UUID,created_at TIMESTAMP WITH TIME ZONE NOT NULL,expires_at TIMESTAMP WITH TIME ZONE NOT NULL)");
        s.executeUpdate("CREATE TABLE IF NOT EXISTS purchases(tx UUID PRIMARY KEY,listing_id UUID NOT NULL,buyer UUID NOT NULL,buyer_name VARCHAR(32) NOT NULL,stage VARCHAR(24) NOT NULL,created_at TIMESTAMP WITH TIME ZONE NOT NULL)");
        s.executeUpdate("ALTER TABLE listings ADD COLUMN IF NOT EXISTS search_text VARCHAR(512) NOT NULL DEFAULT ''");
        s.executeUpdate("CREATE TABLE IF NOT EXISTS auction_audit(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,action VARCHAR(32) NOT NULL,listing_id UUID,transaction_id UUID,actor UUID,detail VARCHAR(512) NOT NULL)");
        s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_listings_state_created ON listings(state,created_at)");
        s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_listings_state_price ON listings(state,price)");
        s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_listings_seller_state ON listings(seller,state)");
        s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_purchases_buyer_stage ON purchases(buyer,stage)");
        s.executeUpdate("DELETE FROM schema_version");s.executeUpdate("INSERT INTO schema_version(version) VALUES(2)");
    }});}

    public CompletableFuture<Listing> create(UUID seller,String name,byte[] item,double price,Instant expires){return createLimited(seller,name,item,price,expires,name,Integer.MAX_VALUE).thenApply(value->value.orElseThrow());}
    public CompletableFuture<Optional<Listing>> createLimited(UUID seller,String name,byte[] item,double price,Instant expires,String searchText,int limit){return supply(()->{
        UUID id=UUID.randomUUID();Instant now=Instant.now();String safeSearch=clean(searchText,512);
        try(Connection c=open()){c.setAutoCommit(false);try{
            expire(c,now);
            try(PreparedStatement count=c.prepareStatement("SELECT COUNT(*) FROM listings WHERE seller=? AND state IN ('ACTIVE','RESERVED')")){count.setObject(1,seller);try(ResultSet r=count.executeQuery()){r.next();if(r.getLong(1)>=Math.clamp(limit,1,100)){c.rollback();return Optional.empty();}}}
            try(PreparedStatement p=c.prepareStatement("INSERT INTO listings(id,seller,seller_name,item,price,state,buyer,created_at,expires_at,search_text) VALUES(?,?,?,?,?,'ACTIVE',NULL,?,?,?)")){p.setObject(1,id);p.setObject(2,seller);p.setString(3,clean(name,32));p.setBytes(4,item);p.setDouble(5,price);p.setObject(6,now);p.setObject(7,expires);p.setString(8,safeSearch);p.executeUpdate();}
            audit(c,"CREATED",id,null,seller,"price="+price);c.commit();return Optional.of(new Listing(id,seller,clean(name,32),item,price,ListingState.ACTIVE,null,now,expires));
        }catch(Throwable error){c.rollback();throw error;}finally{c.setAutoCommit(true);}}
    });}

    public CompletableFuture<BrowsePage> browse(String query,UUID seller,SortOrder sort,int requestedPage,int pageSize){return supply(()->{
        int size=Math.clamp(pageSize,9,45);String needle=clean(query,128).toLowerCase(Locale.ROOT);Instant now=Instant.now();
        try(Connection c=open()){expire(c,now);String where="state='ACTIVE'"+(seller==null?"":" AND seller=?")+(needle.isEmpty()?"":" AND LOCATE(?,LOWER(search_text || ' ' || seller_name))>0");
            int total;try(PreparedStatement p=c.prepareStatement("SELECT COUNT(*) FROM listings WHERE "+where)){bindFilter(p,seller,needle);try(ResultSet r=p.executeQuery()){r.next();total=r.getInt(1);}}
            int pages=Math.max(1,(total+size-1)/size),page=Math.clamp(requestedPage,0,pages-1),offset=page*size;
            String order=switch(sort){case PRICE_LOW->"price ASC,created_at DESC";case PRICE_HIGH->"price DESC,created_at DESC";case EXPIRING->"expires_at ASC,created_at DESC";default->"created_at DESC";};
            List<Listing> output=new ArrayList<>();try(PreparedStatement p=c.prepareStatement("SELECT * FROM listings WHERE "+where+" ORDER BY "+order+" OFFSET ? ROWS FETCH NEXT ? ROWS ONLY")){int index=bindFilter(p,seller,needle);p.setInt(index++,offset);p.setInt(index,size);try(ResultSet r=p.executeQuery()){while(r.next())output.add(map(r));}}
            return new BrowsePage(output,total,page,pages);
        }
    });}

    public CompletableFuture<List<Listing>> active(int limit){return browse("",null,SortOrder.NEWEST,0,Math.clamp(limit,9,45)).thenApply(BrowsePage::listings);}
    public CompletableFuture<Map<UUID,ListingState>> states(Collection<UUID> ids){if(ids.isEmpty())return CompletableFuture.completedFuture(Map.of());return supply(()->{Map<UUID,ListingState>out=new HashMap<>();String marks=String.join(",",Collections.nCopies(Math.min(ids.size(),45),"?"));try(Connection c=open()){expire(c,Instant.now());try(PreparedStatement p=c.prepareStatement("SELECT id,state FROM listings WHERE id IN ("+marks+")")){int i=1;for(UUID id:ids.stream().limit(45).toList())p.setObject(i++,id);try(ResultSet r=p.executeQuery()){while(r.next())out.put(r.getObject(1,UUID.class),ListingState.valueOf(r.getString(2)));}}}return Map.copyOf(out);});}
    public CompletableFuture<Long> activeCount(UUID seller){return supply(()->{try(Connection c=open()){expire(c,Instant.now());try(PreparedStatement p=c.prepareStatement("SELECT COUNT(*) FROM listings WHERE seller=? AND state IN ('ACTIVE','RESERVED')")){p.setObject(1,seller);try(ResultSet r=p.executeQuery()){r.next();return r.getLong(1);}}}});}

    public CompletableFuture<PurchaseResult> reserve(UUID listing,UUID buyer,String buyerName){return supply(()->{try(Connection c=open()){c.setAutoCommit(false);try{Listing value;try(PreparedStatement p=c.prepareStatement("SELECT * FROM listings WHERE id=? FOR UPDATE")){p.setObject(1,listing);try(ResultSet r=p.executeQuery()){if(!r.next()){c.rollback();return PurchaseResult.rejected(PurchaseResult.Status.NOT_FOUND);}value=map(r);}}if(value.seller().equals(buyer)){c.rollback();return PurchaseResult.rejected(PurchaseResult.Status.OWN_LISTING);}if(value.state()!=ListingState.ACTIVE||!value.expiresAt().isAfter(Instant.now())){c.rollback();return PurchaseResult.rejected(PurchaseResult.Status.NOT_ACTIVE);}UUID tx=UUID.randomUUID();try(PreparedStatement p=c.prepareStatement("UPDATE listings SET state='RESERVED',buyer=? WHERE id=? AND state='ACTIVE'")){p.setObject(1,buyer);p.setObject(2,listing);if(p.executeUpdate()!=1){c.rollback();return PurchaseResult.rejected(PurchaseResult.Status.NOT_ACTIVE);}}try(PreparedStatement p=c.prepareStatement("INSERT INTO purchases VALUES(?,?,?,?,'RESERVED',?)")){p.setObject(1,tx);p.setObject(2,listing);p.setObject(3,buyer);p.setString(4,clean(buyerName,32));p.setObject(5,Instant.now());p.executeUpdate();}audit(c,"RESERVED",listing,tx,buyer,"");c.commit();return new PurchaseResult(PurchaseResult.Status.RESERVED,value,tx);}catch(Throwable e){c.rollback();throw e;}finally{c.setAutoCommit(true);}}});}
    public CompletableFuture<Void> stage(UUID tx,String stage){return run(()->{try(Connection c=open();PreparedStatement p=c.prepareStatement("UPDATE purchases SET stage=? WHERE tx=?")){p.setString(1,clean(stage,24));p.setObject(2,tx);p.executeUpdate();}});}
    public CompletableFuture<Void> release(UUID tx,UUID listing){return run(()->{try(Connection c=open()){c.setAutoCommit(false);try(PreparedStatement p=c.prepareStatement("UPDATE listings SET state='ACTIVE',buyer=NULL WHERE id=? AND state='RESERVED'")){p.setObject(1,listing);p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("UPDATE purchases SET stage='RELEASED' WHERE tx=?")){p.setObject(1,tx);p.executeUpdate();}audit(c,"RELEASED",listing,tx,null,"");c.commit();}});}
    public CompletableFuture<Void> sold(UUID tx,UUID listing){return run(()->{try(Connection c=open()){c.setAutoCommit(false);try(PreparedStatement p=c.prepareStatement("UPDATE listings SET state='SOLD' WHERE id=? AND state='RESERVED'")){p.setObject(1,listing);if(p.executeUpdate()!=1)throw new SQLException("Listing is not reserved");}try(PreparedStatement p=c.prepareStatement("UPDATE purchases SET stage='ITEM_PENDING' WHERE tx=?")){p.setObject(1,tx);if(p.executeUpdate()!=1)throw new SQLException("Transaction not found");}audit(c,"SOLD",listing,tx,null,"");c.commit();}});}
    public CompletableFuture<Optional<Listing>> cancel(UUID id,UUID actor,boolean admin){return supply(()->{try(Connection c=open()){c.setAutoCommit(false);try{Listing listing;try(PreparedStatement p=c.prepareStatement("SELECT * FROM listings WHERE id=? FOR UPDATE")){p.setObject(1,id);try(ResultSet r=p.executeQuery()){if(!r.next()){c.rollback();return Optional.empty();}listing=map(r);}}if(listing.state()!=ListingState.ACTIVE||(!admin&&!listing.seller().equals(actor))){c.rollback();return Optional.empty();}try(PreparedStatement p=c.prepareStatement("UPDATE listings SET state='CANCELLED' WHERE id=? AND state='ACTIVE'")){p.setObject(1,id);if(p.executeUpdate()!=1){c.rollback();return Optional.empty();}}audit(c,"CANCELLED",id,null,actor,admin?"admin":"owner");c.commit();return Optional.of(listing);}catch(Throwable e){c.rollback();throw e;}finally{c.setAutoCommit(true);}}});}
    public CompletableFuture<List<Listing>> returns(UUID seller){return supply(()->{List<Listing>out=new ArrayList<>();try(Connection c=open()){expire(c,Instant.now());try(PreparedStatement p=c.prepareStatement("SELECT * FROM listings WHERE seller=? AND state IN ('CANCELLED','EXPIRED') ORDER BY created_at")){p.setObject(1,seller);try(ResultSet r=p.executeQuery()){while(r.next())out.add(map(r));}}}return List.copyOf(out);});}
    public CompletableFuture<Boolean> returned(UUID id,UUID seller){return supply(()->{try(Connection c=open();PreparedStatement p=c.prepareStatement("UPDATE listings SET state='RETURNED' WHERE id=? AND seller=? AND state IN ('CANCELLED','EXPIRED')")){p.setObject(1,id);p.setObject(2,seller);return p.executeUpdate()==1;}});}
    public CompletableFuture<List<PendingDelivery>> pending(UUID buyer){return supply(()->{List<PendingDelivery>out=new ArrayList<>();try(Connection c=open();PreparedStatement p=c.prepareStatement("SELECT p.tx,l.* FROM purchases p JOIN listings l ON l.id=p.listing_id WHERE p.buyer=? AND p.stage='ITEM_PENDING' AND l.state='SOLD' ORDER BY p.created_at")){p.setObject(1,buyer);try(ResultSet r=p.executeQuery()){while(r.next())out.add(new PendingDelivery(r.getObject("tx",UUID.class),map(r)));}}return List.copyOf(out);});}

    private static int bindFilter(PreparedStatement p,UUID seller,String needle)throws SQLException{int i=1;if(seller!=null)p.setObject(i++,seller);if(!needle.isEmpty())p.setString(i++,needle);return i;}
    private static void expire(Connection c,Instant now)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE listings SET state='EXPIRED' WHERE state='ACTIVE' AND expires_at<=?")){p.setObject(1,now);p.executeUpdate();}}
    private static void audit(Connection c,String action,UUID listing,UUID tx,UUID actor,String detail)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO auction_audit(occurred_at,action,listing_id,transaction_id,actor,detail) VALUES(?,?,?,?,?,?)")){p.setObject(1,Instant.now());p.setString(2,action);p.setObject(3,listing);p.setObject(4,tx);p.setObject(5,actor);p.setString(6,clean(detail,512));p.executeUpdate();}}
    private static String clean(String value,int max){String text=value==null?"":value.replaceAll("[\\p{Cntrl}]","").strip();return text.length()<=max?text:text.substring(0,max);}
    private static Listing map(ResultSet r)throws SQLException{return new Listing(r.getObject("id",UUID.class),r.getObject("seller",UUID.class),r.getString("seller_name"),r.getBytes("item"),r.getDouble("price"),ListingState.valueOf(r.getString("state")),r.getObject("buyer",UUID.class),r.getObject("created_at",OffsetDateTime.class).toInstant(),r.getObject("expires_at",OffsetDateTime.class).toInstant());}
    private Connection open()throws SQLException{Properties p=new Properties();p.setProperty("user","sa");p.setProperty("password","");return new Driver().connect(url,p);}
    private<T>CompletableFuture<T>supply(SqlSupplier<T>task){return CompletableFuture.supplyAsync(()->{try{return task.get();}catch(Exception e){throw new CompletionException(e);}},executor);}
    private CompletableFuture<Void>run(SqlRunnable task){return supply(()->{task.run();return null;});}
    @Override public void close(){executor.shutdown();try{if(!executor.awaitTermination(5,TimeUnit.SECONDS))executor.shutdownNow();}catch(InterruptedException error){executor.shutdownNow();Thread.currentThread().interrupt();}}
    @FunctionalInterface private interface SqlSupplier<T>{T get()throws Exception;}@FunctionalInterface private interface SqlRunnable{void run()throws Exception;}
    public record PendingDelivery(UUID transactionId,Listing listing){}
}
