package io.github.miklires.mauction;
import net.milkbowl.vault.economy.Economy;import org.bstats.bukkit.Metrics;import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.inventory.InventoryClickEvent;import org.bukkit.inventory.*;import org.bukkit.plugin.RegisteredServiceProvider;import org.bukkit.plugin.java.JavaPlugin;import java.time.*;import java.util.*;
public final class MAuctionPlugin extends JavaPlugin implements CommandExecutor,TabCompleter,Listener{
 private AuctionRepository repository;private Economy economy;private volatile boolean ready;
 @Override public void onEnable(){saveDefaultConfig();RegisteredServiceProvider<Economy>provider=getServer().getServicesManager().getRegistration(Economy.class);if(provider==null){getLogger().severe("Vault economy provider is required");getServer().getPluginManager().disablePlugin(this);return;}economy=provider.getProvider();repository=new AuctionRepository(getDataFolder().toPath().resolve("auction"));repository.initialize().thenRun(()->{ready=true;getLogger().info("mAuction 1.0.0 is ready");}).exceptionally(e->{getLogger().severe("Storage failed: "+e.getMessage());return null;});PluginCommand command=Objects.requireNonNull(getCommand("auction"));command.setExecutor(this);command.setTabCompleter(this);getServer().getPluginManager().registerEvents(this,this);new Metrics(this,27943);}
 @Override public void onDisable(){if(repository!=null)repository.close();}
 @Override public boolean onCommand(CommandSender sender,Command command,String label,String[]args){if(!(sender instanceof Player player)){sender.sendMessage("§cТолько для игроков.");return true;}if(!ready){player.sendMessage("§cАукцион загружается.");return true;}if(args.length==0){open(player);return true;}switch(args[0].toLowerCase(Locale.ROOT)){case"sell"->{if(args.length<2){player.sendMessage("§c/ah sell <цена>");return true;}sell(player,args[1]);}case"cancel"->{if(args.length<2){player.sendMessage("§c/ah cancel <id>");return true;}try{UUID id=UUID.fromString(args[1]);repository.cancel(id,player.getUniqueId(),player.hasPermission("mauction.admin")).thenAccept(value->player.getScheduler().execute(this,()->{if(value.isEmpty()){player.sendMessage("§cЛот не найден.");return;}give(player,ItemCodec.decode(value.get().item()));player.sendMessage("§aЛот отменён, предмет возвращён.");},null,1));}catch(Exception e){player.sendMessage("§cНекорректный ID.");}}case"reload"->{if(!player.hasPermission("mauction.admin")){player.sendMessage("§cНедостаточно прав.");return true;}reloadConfig();player.sendMessage("§aКонфигурация перезагружена.");}default->player.sendMessage("§c/ah [sell <price>|cancel <id>|reload]");}return true;}
 private void open(Player player){repository.active(45).thenAccept(list->player.getScheduler().execute(this,()->player.openInventory(new AuctionMenu(getConfig().getString("gui-title","Аукцион"),list).getInventory()),null,1));}
 private void sell(Player player,String raw){double price;try{price=Double.parseDouble(raw);if(price<=0||!Double.isFinite(price))throw new NumberFormatException();}catch(NumberFormatException e){player.sendMessage("§cНекорректная цена.");return;}repository.activeCount(player.getUniqueId()).thenAccept(count->player.getScheduler().execute(this,()->{if(count>=getConfig().getInt("listing-limit",10)){player.sendMessage("§cДостигнут лимит лотов.");return;}ItemStack held=player.getInventory().getItemInMainHand();if(held.getType().isAir()){player.sendMessage("§cВозьмите предмет в основную руку.");return;}ItemStack item=held.clone();player.getInventory().setItemInMainHand(null);Instant expires=Instant.now().plus(Duration.ofHours(getConfig().getLong("listing-duration-hours",48)));repository.create(player.getUniqueId(),player.getName(),ItemCodec.encode(item),price,expires).whenComplete((listing,error)->player.getScheduler().execute(this,()->{if(error!=null){give(player,item);player.sendMessage("§cНе удалось создать лот.");}else player.sendMessage("§aЛот создан: §f"+listing.id());},null,1));},null,1));}
 @EventHandler(ignoreCancelled=true)public void click(InventoryClickEvent event){if(!(event.getInventory().getHolder()instanceof AuctionMenu menu))return;event.setCancelled(true);if(!(event.getWhoClicked()instanceof Player player)||event.getClickedInventory()!=event.getInventory())return;menu.listing(event.getSlot()).ifPresent(listing->{player.closeInventory();buy(player,listing.id());});}
 private void buy(Player buyer,UUID id){repository.reserve(id,buyer.getUniqueId(),buyer.getName()).thenAccept(result->global(()->{if(result.status()!=PurchaseResult.Status.RESERVED){buyer.getScheduler().execute(this,()->buyer.sendMessage("§cЛот уже недоступен: "+result.status()),null,1);return;}Listing listing=result.listing();if(!economy.has(buyer,listing.price())){repository.release(result.transactionId(),listing.id());buyer.getScheduler().execute(this,()->buyer.sendMessage("§cНедостаточно средств."),null,1);return;}var withdrawal=economy.withdrawPlayer(buyer,listing.price());if(!withdrawal.transactionSuccess()){repository.release(result.transactionId(),listing.id());buyer.getScheduler().execute(this,()->buyer.sendMessage("§cПлатёж отклонён."),null,1);return;}repository.stage(result.transactionId(),"MONEY_WITHDRAWN");double net=listing.price()*(1-getConfig().getDouble("tax-percent",5)/100.0);var deposit=economy.depositPlayer(Bukkit.getOfflinePlayer(listing.seller()),net);if(!deposit.transactionSuccess()){economy.depositPlayer(buyer,listing.price());repository.release(result.transactionId(),listing.id());buyer.getScheduler().execute(this,()->buyer.sendMessage("§cПокупка отменена: выплата продавцу не прошла."),null,1);return;}repository.stage(result.transactionId(),"SELLER_PAID").thenCompose(v->repository.sold(result.transactionId(),listing.id())).thenRun(()->buyer.getScheduler().execute(this,()->{give(buyer,ItemCodec.decode(listing.item()));repository.stage(result.transactionId(),"DELIVERED");buyer.sendMessage("§aПредмет куплен за §f"+listing.price());},null,1));}));}
 private void give(Player player,ItemStack item){Map<Integer,ItemStack>left=player.getInventory().addItem(item);left.values().forEach(value->player.getWorld().dropItemNaturally(player.getLocation(),value));}private void global(Runnable task){getServer().getGlobalRegionScheduler().execute(this,task);}
 @Override public List<String>onTabComplete(CommandSender sender,Command command,String alias,String[]args){return args.length==1?List.of("sell","cancel","reload").stream().filter(v->v.startsWith(args[0].toLowerCase())).toList():List.of();}
}
